import React, { useState } from 'react';
import {
  Box,
  Typography,
  Button,
  Paper,
  Alert,
  Chip,
  Divider,
  Grid,
  Card,
  CardContent,
  CardActions,
  CircularProgress
} from '@mui/material';
import {
  Download as DownloadIcon,
  CheckCircle as CheckCircleIcon,
  Refresh as RefreshIcon,
  Description as DescriptionIcon
} from '@mui/icons-material';
import { downloadDocument } from '../../services/documentService';

const DocumentGenerationSuccess = ({ 
  generatedDocument, 
  onGenerateAnother, 
  onClose 
}) => {
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState('');



  const handleDownload = async () => {
    setDownloading(true);
    setError('');
    
    try {
      // Extract filename from the generated_file URL or use template name
      const filename = generatedDocument.generated_file 
        ? generatedDocument.generated_file.split('/').pop()
        : `${generatedDocument.template_name}_${new Date().toISOString().split('T')[0]}.pdf`;
      
      await downloadDocument(generatedDocument.id, filename);
    } catch (err) {
      console.error('Download error:', err);
      setError('Failed to download document. Please try again.');
    } finally {
      setDownloading(false);
    }
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleString();
  };

  return (
    <Paper sx={{ p: 3, mb: 3 }}>
      <Box sx={{ display: 'flex', alignItems: 'center', mb: 3 }}>
        <CheckCircleIcon sx={{ mr: 2, color: 'success.main', fontSize: 32 }} />
        <Typography variant="h5" component="h2" color="success.main">
          Document Generated Successfully!
        </Typography>
      </Box>

      {error && (
        <Alert severity="error" sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}

      <Card sx={{ mb: 3 }}>
        <CardContent>
          <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
            <DescriptionIcon sx={{ mr: 1, color: 'primary.main' }} />
            <Typography variant="h6" component="h3">
              {generatedDocument.template_name}
            </Typography>
          </Box>
          
          <Grid container spacing={2}>
            <Grid item xs={12} sm={6}>
              <Typography variant="body2" color="text.secondary">
                <strong>Generated by:</strong> {generatedDocument.generated_by_username}
              </Typography>
            </Grid>
            <Grid item xs={12} sm={6}>
              <Typography variant="body2" color="text.secondary">
                <strong>Department:</strong> {generatedDocument.department_name}
              </Typography>
            </Grid>
            <Grid item xs={12} sm={6}>
              <Typography variant="body2" color="text.secondary">
                <strong>Created:</strong> {formatDate(generatedDocument.created_at)}
              </Typography>
            </Grid>
            <Grid item xs={12} sm={6}>
              <Chip 
                label={generatedDocument.status_display || 'Completed'}
                color="success"
                size="small"
              />
            </Grid>
          </Grid>

          {generatedDocument.parameters && (
            <Box sx={{ mt: 2 }}>
              <Typography variant="body2" color="text.secondary">
                <strong>Parameters:</strong>
              </Typography>
              <Box sx={{ mt: 1 }}>
                {Object.entries(generatedDocument.parameters).map(([key, value]) => (
                  <Chip
                    key={key}
                    label={`${key}: ${value}`}
                    size="small"
                    variant="outlined"
                    sx={{ mr: 1, mb: 1 }}
                  />
                ))}
              </Box>
            </Box>
          )}
        </CardContent>

        <CardActions sx={{ justifyContent: 'flex-start', p: 2 }}>
          <Button
            variant="contained"
            startIcon={downloading ? <CircularProgress size={16} /> : <DownloadIcon />}
            onClick={handleDownload}
            disabled={downloading}
          >
            {downloading ? 'Downloading...' : 'Download PDF'}
          </Button>
        </CardActions>
      </Card>

      <Divider sx={{ mb: 3 }} />

      <Box sx={{ display: 'flex', justifyContent: 'space-between' }}>
        <Button
          variant="outlined"
          startIcon={<RefreshIcon />}
          onClick={onGenerateAnother}
        >
          Generate Another Document
        </Button>
        <Button
          variant="text"
          onClick={onClose}
        >
          Close
        </Button>
      </Box>
    </Paper>
  );
};

export default DocumentGenerationSuccess;
