"""
Django settings for cleantrac_project project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from frontend/.env
FRONTEND_ENV_PATH = BASE_DIR / 'frontend' / '.env'
if FRONTEND_ENV_PATH.exists():
    load_dotenv(dotenv_path=FRONTEND_ENV_PATH)
else:
    print(f"WARNING: .env file not found at {FRONTEND_ENV_PATH}.")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-placeholder-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# Allow our frontend to embed PDFs via <iframe> for same-origin requests.
# This is safe because documents are served from the same domain / network segment.
SECURE_BROWSER_XSS_FILTER = True
# Default clickjacking protection for production
X_FRAME_OPTIONS = "SAMEORIGIN"




ALLOWED_HOSTS = [
    "localhost", "127.0.0.1", "10.0.0.42", "0.0.0.0",
    "cleentrac.com", "www.cleentrac.com",          # front-end
    "api.cleentrac.com",                           # back-end
    "ip-172-31-42-178",          # private hostname is ok
    "172.31.42.178",
    "cleentrac-alb-1566483969.eu-north-1.elb.amazonaws.com",
    "ip-172-31-42-178.eu-north-1.compute.internal",       # For accessing frontend from other devices on the network
    ".manager.13-60-56-181.nip.io",
    # Tenant domains for multi-tenant setup
    "capestation.receiving.cleentrac.com",
    "capestation.manager.cleentrac.com",
]

# Extend ALLOWED_HOSTS with values from environment, e.g. when running on EC2
_extra_hosts = os.getenv("ALLOWED_HOSTS") 
if _extra_hosts:
    # Split by comma, strip whitespace, and ignore empty strings
    ALLOWED_HOSTS += [h.strip() for h in _extra_hosts.split(",") if h.strip()]
    # Deduplicate while preserving order
    seen = set()
    ALLOWED_HOSTS = [h for h in ALLOWED_HOSTS if not (h in seen or seen.add(h))]


# Application definition

# ------------------------------------------------------------------
# Multi-tenant configuration
# ------------------------------------------------------------------
# Split apps into SHARED_APPS (live in the public schema) and
# TENANT_APPS (installed in every tenant schema).  django-tenants
# requires that "django_tenants" and the app containing the tenant
# model ("customers" below) come first in SHARED_APPS.

SHARED_APPS = [
    "django_tenants",          # must be FIRST
    "customers",               # holds Store & StoreDomain models
    # Django foundational apps – live in public schema
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.admin",
    # Third-party apps
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
]

# TENANT_APPS (installed in every tenant schema).  django-tenants
TENANT_APPS = [
    "core.apps.CoreConfig",
]

INSTALLED_APPS = SHARED_APPS + TENANT_APPS

# Tenant configuration
TENANT_MODEL = "customers.Store"
TENANT_DOMAIN_MODEL = "customers.StoreDomain"

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",         # For local frontend development (same machine)
    "http://127.0.0.1:5173",       # Also for local frontend development
    "http://10.0.0.42:5173",
    "https://cleentrac.com",
    "https://www.cleentrac.com",
    
]

# Allow extra origins from env (comma-separated)
_extra_origins = os.getenv("CORS_ALLOWED_ORIGINS")
if _extra_origins:
    CORS_ALLOWED_ORIGINS += [o.strip() for o in _extra_origins.split(",") if o.strip()]

CSRF_TRUSTED_ORIGINS = [
    "https://cleentrac.com",
    "https://www.cleentrac.com",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware - place it high, especially before CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.AllowIframeForMedia",
]

# ------------------------------------------------------------------
# Local-development security relaxations
# ------------------------------------------------------------------
if DEBUG:
    # Allow any site (e.g. Vite on another port) to embed this Django
    # instance in an <iframe>. DO NOT use in production.
    X_FRAME_OPTIONS = "ALLOWALL"
    # Remove the default clickjacking middleware so no X-Frame-Options header is added.
    MIDDLEWARE = [mw for mw in MIDDLEWARE if mw != "django.middleware.clickjacking.XFrameOptionsMiddleware"]



ROOT_URLCONF = "cleantrac_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cleantrac_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # CleanTrac primary DB
    "default": (
        dj_database_url.parse(
            os.environ["DATABASE_CLEANTRAC_URL"], conn_max_age=600, ssl_require=True
        )
        if os.getenv("DATABASE_CLEANTRAC_URL")
        else {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    ),

    # Read-only Traceability database on the same RDS instance
    "traceability": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("TRACEABILITY_DB_NAME"),
        "USER": os.getenv("TRACEABILITY_DB_USER"),
        "PASSWORD": os.getenv("TRACEABILITY_DB_PASSWORD"),
        "HOST": os.getenv("TRACEABILITY_DB_HOST"),
        "PORT": os.getenv("TRACEABILITY_DB_PORT", "5432"),
        "OPTIONS": {
            "sslmode": "require",
            "options": "-c default_transaction_read_only=on",
            "connect_timeout": 5,
        },
    },
}

# Validate that required env vars for the traceability DB are present
_required_keys = ["NAME", "USER", "PASSWORD", "HOST"]
if not all(DATABASES["traceability"][k] for k in _required_keys):
    raise ValueError("Missing TRACEABILITY_DB_* environment variables")

# Route traceability app models to the read-only DB


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Johannesburg"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login Redirect URL
LOGIN_REDIRECT_URL = '/api/'  # Redirect to API root after login

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # For browsable API and Django Admin
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # Default to requiring authentication
    )
}

# Optional: If you want to allow all origins (less secure, use for quick testing only)
# CORS_ALLOW_ALL_ORIGINS = True

# Optional: Allow credentials (cookies, authorization headers) to be sent with requests
CORS_ALLOW_CREDENTIALS = True

# Optional: If you need to allow specific headers beyond the defaults
# CORS_ALLOW_HEADERS = list(default_headers) + [
#     'my-custom-header',
# ]

# Optional: If you need to allow specific methods beyond the defaults (GET, POST, HEAD, OPTIONS)
# CORS_ALLOW_METHODS = list(default_methods) + [
#     'PUT',
#     'DELETE',
# ]
