# Generated by Django 5.2.1 on 2025-05-20 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskinstance",
            options={
                "ordering": ["due_date", "start_time"],
                "verbose_name": "Task Instance",
                "verbose_name_plural": "Task Instances",
            },
        ),
        migrations.AddField(
            model_name="taskinstance",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_tasks",
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="taskinstance",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskinstance",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskinstance",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskinstance",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to="core.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="taskinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                    ("requires_attention", "Requires Attention"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
