# Generated by Django 5.2.1 on 2025-05-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_taskinstance_options_taskinstance_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("pending_review", "Pending Review"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                    ("requires_attention", "Requires Attention"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
