# Generated by Django 5.2.1 on 2025-05-22 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_taskinstance_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cleaningitem",
            name="default_assigned_staff",
            field=models.ManyToManyField(
                blank=True,
                help_text="Default staff typically assigned to this cleaning item.",
                related_name="default_cleaning_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cleaningitem",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("adhoc", "Ad-hoc"),
                    ("quarterly", "Quarterly"),
                    ("annually", "Annually"),
                    ("as_needed", "As Needed"),
                ],
                max_length=20,
            ),
        ),
    ]
