# Generated by Django 5.2.1 on 2025-05-26 11:35

from django.db import migrations

AREA_UNIT_NAMES = [
    "Walk in freezer",
    "Walk in Cold room",
    "Display Fridge 1",
    "Display Fridge 2",
    "Display Fridge 3",
    "Island Freezer",
    "Grab and Go Fridge",
    "Serving Counter 1",
    "Serving Counter 2",
    "Serving Counter 3",
    "Butchery Room",
]

def create_area_units(apps, schema_editor):
    Department = apps.get_model('core', 'Department')
    AreaUnit = apps.get_model('core', 'AreaUnit')

    for department in Department.objects.all():
        for unit_name in AREA_UNIT_NAMES:
            AreaUnit.objects.get_or_create(
                department=department,
                name=unit_name,
                defaults={'description': f'{unit_name} in {department.name}'} # Optional: add a default description
            )

def remove_area_units(apps, schema_editor):
    # This function is for reversing the migration. 
    # It will delete the AreaUnits created by this migration.
    Department = apps.get_model('core', 'Department')
    AreaUnit = apps.get_model('core', 'AreaUnit')

    for department in Department.objects.all():
        for unit_name in AREA_UNIT_NAMES:
            AreaUnit.objects.filter(
                department=department,
                name=unit_name
            ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_areaunit_thermometer_and_more"),
    ]

    operations = [
        migrations.RunPython(create_area_units, reverse_code=remove_area_units),
    ]
