# Generated by Django 5.2.1 on 2025-05-27 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_seed_area_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemperatureCheckAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "am_staff",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member assigned for AM temperature checks.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="am_temperature_check_duties",
                        to="core.userprofile",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager who made or last updated the assignment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="made_temperature_check_assignments",
                        to="core.userprofile",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_check_assignments",
                        to="core.department",
                    ),
                ),
                (
                    "pm_staff",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member assigned for PM temperature checks.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pm_temperature_check_duties",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temperature Check Assignment",
                "verbose_name_plural": "Temperature Check Assignments",
                "ordering": ["assignment_date", "department"],
                "unique_together": {("department", "assignment_date")},
            },
        ),
    ]
