# Generated by Django 5.2.1 on 2025-05-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_temperaturecheckassignment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thermometerverificationassignment",
            name="time_period",
            field=models.CharField(
                choices=[
                    ("AM", "Morning"),
                    ("PM", "Afternoon"),
                    ("BOTH", "Both AM and PM"),
                ],
                default="BOTH",
                max_length=4,
            ),
        ),
        migrations.DeleteModel(
            name="TemperatureCheckAssignment",
        ),
    ]
