# Generated by Django 5.2.1 on 2025-05-28 09:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_thermometerverificationassignment_time_period_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCleaningRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_recorded",
                    models.DateField(
                        help_text="The date for which this cleaning status is recorded."
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Was the cleaning task completed for this day?",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Any comments related to this specific cleaning record.",
                        null=True,
                    ),
                ),
                (
                    "cleaning_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to="core.cleaningitem",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who completed or verified the task for the day.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cleaning_records_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Cleaning Record",
                "verbose_name_plural": "Daily Cleaning Records",
                "ordering": ["-date_recorded", "cleaning_item"],
                "unique_together": {("cleaning_item", "date_recorded")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyTemperatureReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_start_date",
                    models.DateField(
                        help_text="The Monday of the week being reviewed."
                    ),
                ),
                (
                    "review_timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp of when the review was submitted.",
                    ),
                ),
                (
                    "overall_comment",
                    models.TextField(
                        blank=True,
                        help_text="Overall comments for the week's temperature checks.",
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_temperature_reviews",
                        to="core.department",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="temperature_reviews_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Temperature Review",
                "verbose_name_plural": "Weekly Temperature Reviews",
                "ordering": ["-week_start_date", "department"],
                "unique_together": {("department", "week_start_date")},
            },
        ),
    ]
