# Generated by Django 5.2.1 on 2025-05-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_dailycleaningrecord_weeklytemperaturereview"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailycleaningrecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="dailycleaningrecord",
            name="verified_task_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verification_logs",
                to="core.taskinstance",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailycleaningrecord",
            unique_together={
                ("cleaning_item", "date_recorded", "verified_task_instance")
            },
        ),
    ]
