# Generated by Django 5.2.1 on 2025-06-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="supplier_code",
            field=models.CharField(max_length=50),
        ),
    ]
