# Generated by Django 5.2.1 on 2025-06-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_supplier_supplier_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="supplier",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="supplier",
            name="departments",
            field=models.ManyToManyField(
                related_name="suppliers", to="core.department"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="department",
        ),
    ]
