# Generated by Django 5.2.1 on 2025-06-04 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_inventoryitem_inventorytransaction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeProductionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_start_time", models.DateTimeField()),
                ("scheduled_end_time", models.DateTimeField()),
                (
                    "scheduled_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("pending_review", "Pending Review"),
                            ("on_hold", "On Hold"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("none", "No Recurrence"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "recurrence_pattern",
                    models.JSONField(
                        blank=True,
                        help_text="JSON object defining the recurrence pattern",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_production_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_production_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_production_tasks",
                        to="core.department",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_tasks",
                        to="core.recipeproductiontask",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_tasks",
                        to="core.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe Production Task",
                "verbose_name_plural": "Recipe Production Tasks",
                "ordering": ["scheduled_start_time"],
                "indexes": [
                    models.Index(
                        fields=["department", "status"],
                        name="core_recipe_departm_be9ac7_idx",
                    ),
                    models.Index(
                        fields=["assigned_staff"], name="core_recipe_assigne_42f1b4_idx"
                    ),
                    models.Index(
                        fields=["scheduled_start_time"],
                        name="core_recipe_schedul_d12ea1_idx",
                    ),
                ],
            },
        ),
    ]
