# Generated by Django 5.2.1 on 2025-06-04 06:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_recipeproductiontask"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionIngredientUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_code",
                    models.CharField(
                        help_text="Batch or lot code for traceability", max_length=100
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        help_text="Expiration date of the ingredient batch"
                    ),
                ),
                ("quantity_used", models.DecimalField(decimal_places=3, max_digits=10)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_usages",
                        to="core.inventoryitem",
                    ),
                ),
                (
                    "production_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_usages",
                        to="core.recipeproductiontask",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_ingredient_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingredient_usages",
                        to="core.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Ingredient Usage",
                "verbose_name_plural": "Production Ingredient Usages",
                "ordering": ["production_task", "ingredient__ingredient_name"],
                "indexes": [
                    models.Index(
                        fields=["batch_code"], name="core_produc_batch_c_33e7e3_idx"
                    ),
                    models.Index(
                        fields=["expiration_date"],
                        name="core_produc_expirat_7f1a67_idx",
                    ),
                    models.Index(
                        fields=["supplier"], name="core_produc_supplie_32a70f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductionOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "expected_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "yield_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated as (actual/expected)*100",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "quality_rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Quality rating from 1-5", null=True
                    ),
                ),
                (
                    "batch_code",
                    models.CharField(
                        help_text="Batch code for the produced output", max_length=100
                    ),
                ),
                (
                    "production_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("expiry_date", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "production_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="core.recipeproductiontask",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_outputs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Output",
                "verbose_name_plural": "Production Outputs",
                "ordering": ["-production_date"],
                "indexes": [
                    models.Index(
                        fields=["batch_code"], name="core_produc_batch_c_0427d6_idx"
                    ),
                    models.Index(
                        fields=["production_date"],
                        name="core_produc_product_ed68a0_idx",
                    ),
                    models.Index(
                        fields=["expiry_date"], name="core_produc_expiry__76a142_idx"
                    ),
                ],
            },
        ),
    ]
