# Generated by Django 5.2.1 on 2025-06-04 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_productioningredientusage_productionoutput"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeproductiontask",
            name="recipe_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_tasks",
                to="core.recipeversion",
            ),
        ),
    ]
