# Generated by Django 5.2.1 on 2025-06-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_recipeproductiontask_recipe_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionoutput",
            name="production_task",
        ),
        migrations.RemoveField(
            model_name="productionoutput",
            name="recorded_by",
        ),
        migrations.RemoveField(
            model_name="recipeproductiontask",
            name="recipe_version",
        ),
        migrations.AddField(
            model_name="recipeproductiontask",
            name="description",
            field=models.TextField(
                default="Production task",
                help_text="Description of the production task",
            ),
        ),
        migrations.AddField(
            model_name="recipeproductiontask",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True, help_text="Estimated duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="recipeproductiontask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("prep", "Preparation"),
                    ("production", "Production"),
                    ("post_production", "Post-Production"),
                    ("quality_check", "Quality Check"),
                    ("packaging", "Packaging"),
                    ("cleanup", "Cleanup"),
                ],
                default="production",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ProductionIngredientUsage",
        ),
        migrations.DeleteModel(
            name="ProductionOutput",
        ),
    ]
