# Generated by Django 5.2.1 on 2025-06-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_remove_productionoutput_production_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionschedule",
            name="batch_unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilogram"),
                    ("L", "Litre"),
                    ("ea", "Each"),
                    ("case", "Case"),
                ],
                default="kg",
                help_text="Unit for batch_size (kg, L, ea, case)",
                max_length=10,
            ),
        ),
    ]
