# Generated by Django 5.2.1 on 2025-06-23 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_folder_document_folder"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivingRecord",
            fields=[
                (
                    "inventory_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("product_code", models.CharField(max_length=255)),
                ("batch_number", models.CharField(max_length=255)),
                ("supplier_code", models.CharField(max_length=50)),
                (
                    "tracking_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "quantity_remaining",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("unit", models.CharField(max_length=20)),
                (
                    "storage_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("best_before_date", models.DateField(blank=True, null=True)),
                ("received_date", models.DateTimeField()),
                ("status", models.CharField(max_length=20)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receiving Record",
                "verbose_name_plural": "Receiving Records",
                "ordering": ["-received_date"],
                "indexes": [
                    models.Index(
                        fields=["product_code"], name="core_receiv_product_25da73_idx"
                    ),
                    models.Index(
                        fields=["batch_number"], name="core_receiv_batch_n_b683ac_idx"
                    ),
                    models.Index(
                        fields=["supplier_code"], name="core_receiv_supplie_433026_idx"
                    ),
                    models.Index(
                        fields=["department"], name="core_receiv_departm_4de0f5_idx"
                    ),
                ],
            },
        ),
    ]
