# Generated by Django 5.2.1 on 2025-06-23 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_product_alter_receivingrecord_product_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the product used for inventory tracking",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipe_ingredients",
                to="core.product",
            ),
        ),
    ]
