# Generated by Django 5.2.1 on 2025-07-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_recipeproductiontask_completed_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receivingrecord",
            options={
                "managed": False,
                "ordering": ["-received_date"],
                "verbose_name": "Receiving Record",
                "verbose_name_plural": "Receiving Records",
            },
        ),
    ]
