# Generated by Django 5.2.1 on 2025-07-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_receivingrecord_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="receivingrecord",
            table="received_products",
        ),
    ]
