# Generated by Django 5.2.1 on 2025-08-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_add_created_by_to_taskinstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("temperature", "Temperature Log"),
                    ("cleaning", "Cleaning Schedule"),
                    ("verification", "Thermometer Verification"),
                    ("recipe", "Recipe Traceability"),
                    ("general", "General Purpose"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
