name: Traceability DB health check

on:
  push:
    branches: [main, calendar_overhaul]
  pull_request:
    branches: [main, calendar_overhaul]

jobs:
  db-health:
    runs-on: ubuntu-latest
    # Ensure required secrets exist in repo settings or environment.
    env:
      TRACEABILITY_DB_NAME: ${{ secrets.TRACEABILITY_DB_NAME }}
      TRACEABILITY_DB_USER: ${{ secrets.TRACEABILITY_DB_USER }}
      TRACEABILITY_DB_PASSWORD: ${{ secrets.TRACEABILITY_DB_PASSWORD }}
      TRACEABILITY_DB_HOST: ${{ secrets.TRACEABILITY_DB_HOST }}
      TRACEABILITY_DB_PORT: ${{ secrets.TRACEABILITY_DB_PORT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system packages           # keep first
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run traceability DB health check  # ← add back
        run: |
          python manage.py check_traceability_db --expected 1